galleryimg command
SUSE-Enceladus/azure-img-utils pull request #39
Opened 2022-06-13 14:25 UTC by apozsuse

Command for galleryimg management

- Includes 3 subcommands for existence check, creation and deletion of a galleryimg
- Update of the README.md and the unit tests accordingly

# Remarks

Due to the Azure SDK replying always None for the result of the async delete operation, it's not possible to provide more accurate info for the user about the image deletion (without implementing some logic). [This issue](https://github.com/SUSE-Enceladus/azure-img-utils/issues/37) has been created to revisit this behavior in the future.

2022-06-13 19:56 UTC, smarlowucf requested changes
Looks good, although I think we want to be clear with naming.

2022-06-13 19:56 UTC, smarlowucf commented on README.md
> +The subcommand is *azure-img-utils galleryimg exists*.
Although the command will be quite long I think we need to be clear on what the sub-command is for. Gallery Images are a different topic. Here we are only handling Gallery Image Versions. Thus I'd suggest the sub-command like gallery-img-versions or gallery-image-versions.

2022-06-14 09:45 UTC, apozsuse commented on azure_img_utils/cli/galleryimg.py
> +    '--image-version',
Done!

2022-06-16 11:16 UTC, rjschwei requested changes

2022-06-16 11:16 UTC, rjschwei commented on README.md
> + in one blob.
s/in one/on a/

2022-06-16 11:16 UTC, rjschwei commented on azure_img_utils/cli/gallery_image_version.py
> +    Deletes an gallery image if the image exists in the gallery
s/an/a/

2022-06-16 13:21 UTC, rjschwei approved these changes

2022-06-16 13:58 UTC, smarlowucf approved these changes

2022-06-16 14:48 UTC, merged